### ISSUE TITLE
Ephemeral nodes are copied

### ISSUE THREAD

**Issue by tylerhawkes** [kshchepanovskyi/zkcopy#11]
Currently, ephemeral nodes are copied, which is a problem when taking backups (or moving to a new cluster) of some schema like say kafka since it will prevent the service from starting up if a restore is done.
I've added a flag that allows nodes to be ignored in https://github.com/kshchepanovskyi/zkcopy/pull/10 
If it is accepted, an updated maven release and new docker image would be great to have.

**Comment by kshchepanovskyi** [comment]
Sure, docker image will be updated automatically once we merge it.

**Comment by kshchepanovskyi** [comment]
P.S. There is no maven release for this project, as it is not deployed to the maven central.

**Comment by tylerhawkes** [comment]
I don't know what you want to do about versioning. I can bump it to 1.3 for the new feature or we can do a 1.2.1 release.

**Comment by kshchepanovskyi** [comment]
Ok, I'll bump version + update docs.

**Comment by kshchepanovskyi** [comment]
I just merged PR, so new docker image should be available soon.
