### ISSUE TITLE
Filter + Rename + Dry run

### ISSUE THREAD

**Issue by naude-r** [kshchepanovskyi/zkcopy#18]
We would like to see 2 new options:
1. filter -> allow one to copy only keys that matches a specific filter
2. rename -> match regex and rename
3. ideally a dry run option as well to be able to test / verify behaviour.

**Comment by kshchepanovskyi** [comment]
Thank you for the suggestion. I'll gladly accept PR for filtering support. Rename is more questionable as more complicated.
